." Manpage for sudokun.
." Contact Benjamin Nguyen <ima.techmoocher@gmail.com> in case of bugs or errors.
.TH SUDOKUN 6 "June 2026" "sudokun v1.0.0" "sudokun man page"

.SH NAME
sudokun \- ncurses-based CLI sudoku game

.SH SYNOPSIS
.BR sudokun
[\-v | \-h]
.br
.BR sudokun
[\-c] [\-r] [\-d \fIdifficulty\fR] [\-s \fIinput_stream\fR]
.br
.BR sudokun
[\fB\-c\fR] \fB\-o\fR
.br
.BR sudokun
\fB\-p\fR \fIexpected_filename.pdf\fR [\fB\-S\fR \fIpaper_size\fR]
.br
.BR sudokun
\fB\-P\fR \fIexpected_filename.png\fR

.SH DESCRIPTION
.BR sudokun
is an ncurses-based sudoku game designed to help you entertain after\&
long working hours without the need to leave the terminal.

.SH OPTIONS

.B \-v
.br
Prints the version information.

.B \-h
.br
Prints the help menu.

.B \-r
.br
Resumes your saved game.
The saved game is stored in $XDG_STATE_HOME/sudokun/ and will be deleted upon a successful resume.

.BR \-c
.br
Disables color mode and switches to using black and white only\&
(useful in case your terminal doesn't support colors).

.B \-o
.br
Outputs stream.
Prints a single sudoku onto standard output. Notation is in stream format like used by -s.

.B \-d <\fIdifficulty\fR>
.br
Chooses difficulty.
Available options are: \fIeasy\fR, \fInormal\fR, \fIhard\fR.

.B \-s <\fIinput_stream\fR>
.br
Passes a user-provided stream to be used as a puzzle.
\fBsudokun\fR will not generate anything but use the provided stream directly.
The provided input should be in stream format, i.e. everthing in one line and use dots (.) for empty fields.
.br
Example: \fBsudokun -s\fR \fI4.....8.5.3..........7......2.....6.....8.4......1.......6.3.7.5..2.....1.4......\fR

.B \-p <\fIoutput_filename.pdf\fR>
.br
Exports a game into a PDF.
Must be followed by an expected filename.
Generates a single sudoku per PDF.
Example: \fBsudokun -p\fR \fIexample.pdf\fR

.B \-S
Paper size for PDF output.
Accepted values are: 'a4' (default), 'a5', 'letter', 'legal', 'oficio', 'invoice', or 'WIDTHxHEIGHT[unit]'. If not given, the unit defaults to centimeters. This can only be used with -p.
Example: \fBsudokun -p\fR \fIexample.pdf\fR \fB-S\fR \fI11x8.5in\fR

.B \-P
Exports a game into a PNG.
Must be followed by an expected filename.
Example: \fBsudokun -P\fR \fIsudoku.png\fR

.SH KEYBINDINGS

Use [h][j][k][l] or arrow keys ([←][↓][↑][→]) to navigate.

Press a number [1-9] to fill the current cell.

Use [Delete], [Backspace], or [x] to clear the current cell.

.BR [c]
Check whether your current solution is correct.
You can use this anytime, after you have finished solving or during the game.

.BR [H]
Fill in one number as a hint.
This feature will not work if you are close to finishing AND/OR\&
having misplaced number(s) in your current solution.

.BR [m]
Toggle marks. If enabled, the number in the currently selected cell will be highlighted in all other cells they occur in.
Only works when colors are enabled.

.BR N
Create a new puzzle.

.BR G
Save current game state.

.BR Q
Exit sudokun.

.BR r
Redraw screen. In case you resized your terminal this will come handy.

.BR S
Let the computer solve the puzzle.

.BR x
Delete number from field.

.BR u
Undo previous action.

.SH BUGS
No known existing bugs.

.SH AUTHOR
Benjamin Nguyen (techmoocher) <ima.techmoocher@gmail.com>

.SH SEE ALSO
Visit
.UR https://github.com/techmoocher/sudokun.git
techmoocher/sudokun
.UE
to learn more.
