/*
 * sudokun
 *
 * Copyright (C) 2026 Benjamin "techmoocher" Nguyen
 *
 * LICENSE:
 *
 * This program is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by 
 * the Free Software Foundation, either version 3 of the License, or 
 * any later version.
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/*** INCLUDES ***/
#include "sudoku.h"
#include "utils.h"

#include <cairo.h>              // cairo_*()
#include <cairo-pdf.h>          // cairo_pdf_surface_create
#include <stdio.h>              // snprintf()
#include <stdlib.h>             // free()

typedef struct {
    int x;
    int y;
} DUPLE_INT;

typedef struct {
    double x;
    double y;
} DUPLE_DOUBLE;

#define RECT_SIZE(type) ((type) 50)
#define SUDOKU_SIZE(type) ((RECT_SIZE(type)) * ((type) 9))
#define SUDOKU_SPACE(type, pad) ((SUDOKU_SIZE(type)) + ((type) pad))

/*** FUNCTIONS ***/

void draw_grid(const char* stream, cairo_t *cr) {
    int rectangle_size = RECT_SIZE(int);

    // small rectangles
    cairo_set_line_width(cr, 1);
    for (int x = 0; x < 9; x++) {
        for (int y = 0; y < 9; y++) {
            cairo_rectangle(cr, x*rectangle_size, y*rectangle_size, rectangle_size, rectangle_size);
        }
    }
    cairo_stroke(cr);

    // large rectangles
    cairo_set_line_width(cr, 4);
    for (int x = 0; x < 3; x++) {
        for (int y = 0; y < 3; y++) {
            cairo_rectangle(cr, x * rectangle_size * 3, y * rectangle_size * 3, rectangle_size * 3, rectangle_size * 3);
        }
    }
    cairo_stroke(cr);

    // numbers
    cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, 25.0);
    int c;
    char tmp_str[2];
    for (int row = 0; row < 9; row++) {
        for (int col = 0; col < 9; col++) {
            c = stream[row*9+col];
            if (c != '.') {
                cairo_move_to(cr, rectangle_size/3 + rectangle_size * row, rectangle_size/1.5 + rectangle_size * col);
                snprintf(tmp_str, 2, "%c", c);
                cairo_show_text(cr, tmp_str);
            }
        }
    }
}

static void prepare_pdf_page(cairo_t *cr, int difficulty) {
    cairo_set_source_rgb(cr, 0, 0, 0);
    cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);

    cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, 10.0);

    // Use snprintf() in case the translation for $(difficulty) is very long
    char tmp_str[512];
    snprintf(tmp_str, 512, "Difficulty: %s", difficulty_to_str(difficulty));

    cairo_move_to(cr, 50.0, 70.0);
    cairo_show_text(cr, tmp_str);
    cairo_move_to(cr, 50.0, 80.0);
    cairo_show_text(cr, "Generated by sudokun - https://techmoocher.github.io/sudokun");

    cairo_save(cr);
    cairo_scale(cr, 0.5, 0.5);
}

static int finish_pdf_generation(cairo_surface_t *surface, cairo_t *cr, bool successful) {
    cairo_restore(cr);

    if (successful)
        cairo_show_page(cr);

    cairo_destroy(cr);
    cairo_surface_destroy(surface);

    return successful ? EXIT_SUCCESS : EXIT_FAILURE;
}

int generate_pdf(int difficulty, PAPER_SIZE paperSize, const char* filename) {
    cairo_surface_t *surface;
    cairo_t *cr;

    PAPER_SIZE ps_points = papersize_normalize(paperSize);
    surface = cairo_pdf_surface_create(filename, ps_points.width, ps_points.height);
    cr = cairo_create(surface);

    prepare_pdf_page(cr, difficulty);

    DUPLE_INT start = { 100, 270 };

    cairo_translate(cr, start.x, start.y);

    char* stream;
    stream = generate_puzzle(difficulty);

#ifdef DEBUG
    printf("0: %s\n", stream);
#endif // DEBUG

    draw_grid(stream, cr);

    cairo_translate(cr, -start.x, -start.y);

    free(stream);

    return finish_pdf_generation(surface, cr, true);
}

void generate_png(int difficulty, char* filename) {
    cairo_surface_t *surface;
    cairo_t *cr;

    surface = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, 453, 453);
    cr = cairo_create(surface);

    cairo_set_source_rgb(cr, 0, 0, 0);
    cairo_set_line_cap(cr, CAIRO_LINE_CAP_SQUARE);

    cairo_select_font_face(cr, "Sans", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, 10.0);

    char* stream;
    stream = generate_puzzle(difficulty);

    cairo_translate(cr, 2, 2);
    draw_grid(stream, cr);
    cairo_surface_write_to_png(surface, filename);

    cairo_destroy(cr);
    cairo_surface_destroy(surface);

    free(stream);
}

int export_generated_file(int difficulty, char* filename, bool isPDF, PAPER_SIZE paperSize) {
    int exit_code = EXIT_SUCCESS;

    if (isPDF) {
        exit_code = generate_pdf(difficulty, paperSize, filename);
    }
    else {
        generate_png(difficulty, filename);
    }

    return exit_code;
}
